// Single source of truth for all UI copy in the app.
// To add a language: add a new top-level key here with the same shape as `en`.
// Data coming from Firestore (product names, categories, addresses, user content, etc.)
// is NOT part of this file and must stay untouched — this file only covers static UI text.

export const strings = {
  en: {
    common: {
      search: 'Search',
      seeAll: 'See all ›',
      seeAllPlain: 'See all',
      cancel: 'Cancel',
      backToTop: 'Back to top ↑',
      locked: 'Locked',
      unlocked: 'Unlocked',
      apply: 'Apply',
      ok: 'OK',
    },
    tabBar: {
      home: 'Home',
      categories: 'Categories',
      buyAgain: 'Buy Again',
      deals: 'Deals',
    },
    home: {
      deliveryTime: '7 minutes',
      locationUnavailable: 'Location unavailable',
      searchHints: ['milk', 'fruits', 'veggies', 'bread', 'eggs', 'chocolate', 'butter', 'chips'],
      searchForPrefix: 'Search for',
      handpickedEssentials: 'Handpicked Daily Essentials',
      noProductsYet: 'No products available yet!',
      failedToLoadProducts: 'Failed to load products.',
      unlockFreeDelivery: 'Unlock free delivery',
      freeDeliveryUnlocked: ' Free delivery unlocked!',
      shopMoreForDelivery: (amount: number) => `Shop ₹${amount} more`,
      cartLabel: 'Cart',
      itemsCount: (n: number) => `${n} item${n !== 1 ? 's' : ''}`,
      offersToggle: 'Offers  ↑',
      offersForYou: 'Offers For You',
      offersCountLabel: '3 offers',
      freeDelivery: 'Free Delivery',
      freeDeliveryUnlockedOnOrder: 'Unlocked on this order!',
      addMoreToUnlockDelivery: (amount: number) => `Add ₹${amount} more to unlock`,
      off50: '₹50 OFF',
      shopMoreFor50: 'Shop for ₹599 more to apply',
      off100: '₹100 OFF',
      shopMoreFor100: 'Shop for ₹1199 more to apply',
    },
    allProducts: {
      screenTitle: 'All Categories',
    },
    previousOrders: {
      headerTitle: 'Your Orders',
      noOrdersYet: 'No orders yet',
    },
    location: {
      permissionTitle: 'Location Permission',
      permissionMessage: 'QuickKart needs access to your location to show nearby stores.',
      askMeLater: 'Ask Me Later',
      unknownLocation: 'Unknown Location',
      locationUnavailableCaps: 'Location Unavailable',
      locationUnavailable: 'Location unavailable',
      couldNotRetrieveLocation: 'Could not retrieve your location.',
      permissionNotGranted: 'Permission to access location was not granted.',
      permissionPermanentlyDenied: 'Location access is permanently denied. Please enable it in Settings.',
      loadingAddress: 'Loading address...',
    },
    floatingCartPanel: {
      freeDeliveryUnlocked: 'Free delivery unlocked!',
    },
    priceFilterBadge: {
      all: 'All',
      under: 'Under',
      prices: 'Prices',
    },
    shareProduct: {
      title: 'Share Product',
      priceLabel: (price: number) => `Rs. ${price}`,
      shareMessage: (name: string, price: number) => `${name} — Rs. ${price}\nScan to open in QuickKart`,
      scanToOpen: 'Scan to open in QuickKart',
      shareQrCode: 'Share QR Code',
    },
    productCard: {
      loginForNotifications: 'Please log in to get notifications',
      enableNotificationsInSettings: 'Enable notifications in Settings',
      willNotifyWhenBack: "We'll notify you when it's back!",
      failedToSubscribe: 'Failed to subscribe. Try again.',
      outOfStock: 'This item is out of stock',
      notify: 'Notify',
      offAmount: (amount: number) => `₹${amount} OFF`,
      add: 'ADD',
    },
    stockBadge: {
      soldOut: 'Sold Out',
    },
    productFilterSheet: {
      selectMaxPrice: 'Select max price',
      inStockOnly: 'In Stock Only',
      offersOnly: 'Offers Only',
      filters: 'Filters',
      moreFilters: 'More Filters',
      clearAll: 'Clear all',
      showProductsCount: (n: number) => `Show ${n} products`,
      showProducts: 'Show products',
    },
    banners: {
      failedToLoad: 'Failed to load banners',
    },
    categoryProducts: {
      noProductsInCategory: (name: string) => `We couldn't find any products in ${name}.`,
      noMatches: 'No matches',
      tryAdjustingFilters: 'Try adjusting your filters.',
    },
    brandProducts: {
      noProductsFound: 'No products found',
      noProductsFromBrand: (brand: string) => `We couldn't find any products from ${brand}.`,
      productsCount: (n: number) => `${n} product${n !== 1 ? 's' : ''}`,
    },
    coupons: {
      headerTitle: 'Coupon & Offers',
      haveACode: 'Have a code?',
      couponsTab: 'Coupons',
      paymentOffersTab: 'Payment Offers',
      note: 'Note: You can now apply coupons and payment offers together.',
      autoAppliedBrandAddOns: 'AUTO-APPLIED BRAND ADD-ONS',
      haveACouponCodeTitle: 'Have a coupon code? Apply here!',
      couponCodeLabel: 'Coupon Code',
      enterCouponCodePlaceholder: 'Enter coupon code',
    },
    productDetails: {
      loginForNotifications: 'Please log in to get notifications',
      notificationCancelled: 'Notification cancelled',
      enableNotificationsInSettings: 'Enable notifications in Settings',
      willNotifyWhenBackInStock: "We'll notify you when it's back in stock!",
      somethingWentWrong: 'Something went wrong. Try again.',
      stockLimitReached: 'Stock limit reached',
      discountOff: (pct: number) => `${pct}% OFF`,
      viewAllBrandProducts: (brand: string) => `View all ${brand} products`,
      weightFallback: '1 unit',
      inclusiveOfTaxes: 'Inclusive of all taxes',
      productDetailsHeading: 'Product Details',
      pleaseWait: 'Please wait…',
      notified: 'Notified',
      notifyMe: 'Notify Me',
      addToCart: 'Add to cart',
      viewCart: 'View Cart',
    },
    orderTracking: {
      title: 'Order Tracking',
    },
    orderPlaced: {
      title: 'Order Placed!',
      subtitle: 'Your order has been confirmed\nand will be delivered soon.',
    },
    notifications: {
      orderPlacedTitle: '🛒 Order Placed!',
      orderPlacedBody: (orderTotal: number) => `Your order of ₹${orderTotal} has been placed successfully. We'll deliver soon!`,
      orderDeliveredTitle: '📦 Order Delivered!',
      orderDeliveredBody: 'Your order has been delivered. Enjoy your items!',
    },
    orderDetails: {
      pdfGenFailedTitle: 'PDF Generation Failed',
      pdfGenFailedMessage: 'Could not generate the invoice. Please try again.',
      couldNotOpenFileTitle: 'Could Not Open File',
      couldNotOpenFileMessage: 'PDF was saved but could not be opened. Try a PDF viewer app.',
      couldNotLoadOrder: 'Order details record could not be loaded.',
      orderIdLabel: (id: string) => `Order #${id}`,
      itemsCount: (n: number) => `${n} ${n === 1 ? 'item' : 'items'}`,
      getHelp: 'Get Help',
      orderDelivered: 'Order Delivered',
      orderCancelled: 'Order Cancelled',
      orderPlaced: 'Order Placed',
      deliveredSubtitle: (date: string) => `Your items were delivered on ${date}`,
      cancelledSubtitle: (date: string) => `Order was cancelled on ${date}`,
      placedSubtitle: (date: string) => `Order placed on ${date}. Delivery in progress.`,
      productsOrdered: 'Products Ordered',
      productSnapshotFallback: 'Product Snapshot',
      unitSizeFallback: 'Unit Size',
      weightAndUnits: (weight: string, quantity: number) => `${weight}  •  ${quantity} ${quantity === 1 ? 'unit' : 'units'}`,
      promoVoucherApplied: (code: string) => `Promo Voucher (${code}) Applied`,
      totalBill: 'Total Bill',
      downloadInvoice: 'Download Invoice / Credit Note',
      orderDetailsHeading: 'Order Details',
      orderIdFieldLabel: 'Order ID',
      receiverDetailsLabel: 'Receiver Details',
      deliveryAddressLabel: 'Delivery Address',
      orderPlacedAtLabel: 'Order Placed at',
      needHelpTitle: 'Need help with this order?',
      needHelpSubtitle: 'Find your issue or reach out via chat',
    },
    previousOrdersCard: {
      orderStatus: (status: string) => `Order ${status} `,
      placedAt: (dateString: string) => `Placed at ${dateString}`,
      orderAgain: 'Order Again',
    },
    buyAgain: {
      filterTabs: {
        all: 'All Items',
        fresh: 'Fruits &\nVegetables',
        dairy: 'Dairy\nProducts',
        snacks: 'Snacks &\nDrinks',
        electronics: 'Grocery &\nKitchen',
      },
      headerTitle: 'Buy Again ',
      buyAgainSection: 'Buy Again',
      noOrdersYet: "You haven't ordered anything yet.",
      noBoughtItemsInCategory: 'No previously bought items in this category.',
      allProducts: 'All Products',
      noProductsAvailable: 'No products available.',
      taglineLine1: 'The place that fits all',
      taglineLine2: 'your needs',
    },
    managePayments: {
      headerTitle: 'Manage Payments',
      upiManagementTitle: 'QuickKart UPI Management',
      upiManagementSub: 'Manage everything related to QuickKart UPI',
      wallets: 'Wallets',
      amazonPayBalance: 'Amazon Pay Balance',
      link: 'Link',
      payLater: 'Pay Later',
      amazonPayLater: 'Amazon Pay Later',
    },
    wishlist: {
      headerTitle: 'Wishlist',
      emptyTitle: 'Your wishlist is empty',
      emptySubtitle: 'Tap the heart on any product to save it here',
    },
    profileEdit: {
      headerTitle: 'Profile',
      failedToLoadProfile: 'Failed to load profile',
      nameEmpty: 'Name cannot be empty',
      success: 'Success',
      profileUpdated: 'Profile updated successfully',
      failedToUpdateProfile: 'Failed to update profile',
      deleteAccountTitle: 'Delete Account',
      deleteAccountConfirm: 'Are you sure? This will permanently remove all your orders, wallet amount and any active referral codes.',
      failedToDeleteAccount: 'Please sign out and sign back in before deleting your account.',
      nameLabel: 'Name *',
      namePlaceholder: 'Your name',
      mobileLabel: 'Mobile Number *',
      mobilePlaceholder: 'Mobile number',
      emailLabel: 'Email Address *',
      emailPlaceholder: 'Email address',
      emailHint: 'We promise not to spam you',
      saving: 'Saving...',
      submit: 'Submit',
      deleteAccountDesc: 'Deleting your account will remove all your orders, wallet amount and any active referral codes.',
    },
    rewards: {
      headerTitle: 'Rewards',
    },
    refunds: {
      headerTitle: 'Refunds',
      emptyTitle: 'No Refunds Yet',
      emptySubtitle: 'When a refund is processed, it will appear here.',
    },
    policy: {
      headerTitle: 'Policies',
      emptyTitle: 'No Policies Yet',
      emptySubtitle: 'Our policies and terms will be available here soon.',
    },
    addressForm: {
      addAddressTitle: 'Add Address',
      editAddressTitle: 'Edit Address',
      labelField: 'Label (Home / Work / Other)',
      labelPlaceholder: 'e.g. Home',
      houseNoField: 'House / Flat No.',
      houseNoPlaceholder: 'e.g. 42B',
      apartmentField: 'Apartment / Society',
      apartmentPlaceholder: 'e.g. Sunrise Apartments',
      landmarkField: 'Landmark',
      landmarkPlaceholder: 'e.g. Near City Mall',
      fullAddressField: 'Full Address',
      fullAddressPlaceholder: 'Street, City, Pin code',
      saveAddress: 'Save Address',
      saving: 'Saving…',
    },
    addressCard: {
      default: 'Default',
      nearLandmark: (landmark: string) => `Near ${landmark}`,
      editAddress: 'Edit Address',
    },
    addressList: {
      headerTitle: 'Saved Addresses',
      noSavedAddresses: 'No saved addresses',
      addNewAddress: 'Add New Address',
    },
    profile: {
      headerTitle: 'Profile',
      errorTitle: 'Error',
      failedToLoadProfile: 'Failed to load profile',
      logOutTitle: 'Log Out',
      logOutConfirm: 'Are you sure you want to log out?',
      logoutFailed: 'Logout failed',
      suggestionThanksTitle: 'Thank you!',
      suggestionThanksMessage: 'Your suggestion has been received.',
      yourOrders: 'Your\nOrders',
      helpAndSupport: 'Help &\nSupport',
      yourWishlist: 'Your\nWishlist',
      yourInformation: 'Your Information',
      yourRefunds: 'Your Refunds',
      yourWishlistTitle: 'Your Wishlist',
      eGiftCards: 'E-Gift Cards',
      comingSoon: 'Coming soon!',
      helpAndSupportTitle: 'Help & Support',
      account: 'Account',
      savedAddresses: 'Saved Addresses',
      addressesCount: (n: number) => `${n} Address${n !== 1 ? "es" : ""}`,
      editProfile: 'Edit Profile',
      managePayments: 'Manage Payments',
      rewards: 'Rewards',
      other: 'Other',
      suggestProducts: 'Suggest Products',
      policies: 'Policies',
      logOutButton: 'Log Out',
      suggestSheetSub: "Didn't find what you are looking for? Please suggest the products",
      suggestPlaceholder: 'Enter the name of the products you would like to see on Zepto.',
      send: 'Send',
      language: 'Language',
      selectLanguage: 'Select Language',
    },
    validators: {
      nameRequired: 'Name is required',
      contactRequired: 'Contact is required',
      emailInvalid: 'Email is invalid',
      emailRequired: 'Email is required',
      invalidEmail: 'Invalid email',
      passwordMinLength: 'Password must be at least 6 characters',
      passwordsDoNotMatch: 'Passwords do not match',
      passwordRequired: 'Password is required',
    },
    auth: {
      pleaseFixFields: 'Please fix the highlighted fields.',
      loginFailed: 'Login failed. Please try again.',
      welcomeToQuickkart: 'Welcome to QuickKart',
      pleaseLoginToAccount: 'Please login to your account',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      loggingIn: 'Logging in...',
      login: 'Login',
      dontHaveAccount: "Don't have an account?",
      signUp: ' Sign Up',
      createAnAccount: 'Create an Account',
      joinAndStartShopping: 'Join QuickKart and start shopping',
      fullNameLabel: 'Full Name',
      phoneNumberLabel: 'Phone Number',
      confirmPasswordLabel: 'Confirm Password',
      creatingAccount: 'Creating account...',
      signUpButton: 'Sign Up',
      alreadyHaveAccount: 'Already have an account?',
      logIn: ' Log In',
      failedToCreateAccount: 'Failed to create an account. Please try again.',
    },
    searchHeader: {
      defaultPlaceholder: 'Search for products...',
    },
    searchResults: {
      priceChipLabel: 'Price',
      resultsCount: (n: number) => `${n} result${n !== 1 ? 's' : ''}`,
      inSubCategory: (name: string) => ` in "${name}"`,
      forQuery: (query: string) => ` for "${query}"`,
      noProductsForQuery: (query: string) => `No products found for "${query}"`,
    },
    deals: {
      priceTabs: {
        under199: 'Under ₹199',
        under299: 'Under ₹299',
        under399: 'Under ₹399',
        under499: 'Under ₹499',
        allPrices: 'All Prices',
      },
      categorySections: {
        fresh: 'Fresh Produce',
        dairy: 'Dairy Products',
        snacks: 'Snacks & Beverages',
        electronics: 'Kitchen & More',
      },
      saleTitle: 'Sale',
      salePicks: ' Sale Picks',
      itemsCount: (n: number) => `${n} items`,
      seeAll: 'See All',
      noProductsUnder: (amount: string | number) => `No products under ₹${amount}`,
      thisRange: 'this range',
      tryDifferentPriceRange: 'Try a different price range',
    },
    scheduleModal: {
      scheduleYourOrder: 'Schedule your order',
      oneShipment: '1 shipment',
      shipment: 'Shipment',
      oneOfOne: '1 of 1',
      itemsCount: (n: number) => `${n} Item${n !== 1 ? 's' : ''}`,
      viewItems: 'View items',
      highDemand: 'High Demand!',
      instantUnavailableNote: 'Instant delivery is temporarily unavailable. Schedule for later.',
      instantDelivery: 'Instant Delivery',
      unavailable: 'Unavailable',
      scheduleDelivery: 'Schedule Delivery',
      dateSlotFormat: (dateLabel: string, slotDisplay: string) => `${dateLabel}, ${slotDisplay}`,
      selectASlot: 'Select a slot',
      today: (dateLabel: string) => `Today, ${dateLabel}`,
      tomorrow: (dateLabel: string) => `Tomorrow, ${dateLabel}`,
      slotsCount: (n: number) => `${n} Slots`,
      earliest: 'EARLIEST',
      afternoon: 'AFTERNOON',
      evening: 'EVENING',
      lessSlots: 'Less Slots',
      moreSlots: 'More Slots',
      cancelNote: 'You can cancel up to 30 min prior to delivery time',
      confirm: 'Confirm',
      shipmentOneOfOne: 'Shipment 1 of 1',
      itemsCountLower: (n: number) => `${n} items`,
      weightByQty: (weight: string, quantity: number) => `${weight} X ${quantity} piece(s)`,
    },
    savingsCard: {
      totalSavings: 'Total savings on this order',
      youSave: (amount: number) => `You save ₹${amount}`,
    },
    deliveryTip: {
      tipDeliveryPartner: 'Tip Delivery Partner',
      subtitle: '100% goes directly to them',
      clear: 'Clear',
    },
    couponCard: {
      title: 'Coupons & offers',
      viewCoupons: 'View coupons',
      viewAllPaymentOffers: 'View all payment offers >',
      remove: 'Remove',
      viewPaymentOffers: 'View payment offers',
    },
    brandCoupon: {
      autoApplied: 'Coupon will be auto-applied',
      knowMore: 'Know more',
      unlockLine: (unlockText: string) => `• ${unlockText} to apply this offer`,
      autoAppliedLine: '• Coupon will be automatically applied at checkout',
      validOnBrandLine: '• Valid on qualifying products from this brand only',
    },
    billSummary: {
      title: 'Bill Summary',
      itemTotal: 'Item Total',
      deliveryFee: 'Delivery Fee',
      free: 'FREE',
      freeAboveNote: (amount: number) => `Free above ₹99 (Unlock by adding ₹${amount} more)`,
      handlingFee: 'Handling Fee',
      deliveryTip: 'Delivery Tip',
      toPay: 'To Pay',
      savingsOnOrder: 'Savings on this order',
      discountOnMrp: 'Discount on MRP',
    },
    addressSelector: {
      selectAddress: 'Select Address',
      addNewAddress: 'Add New Address',
      savedAddresses: 'Saved Addresses',
      selected: 'Selected',
      deleteAddressTitle: 'Delete Address',
      deleteAddressMessage: 'Are you sure you want to delete this address?',
      delete: 'Delete',
    },
    addressHeader: {
      defaultTitle: 'Home',
      defaultAddress: 'Delivering to your saved address',
      deliveringTo: 'Delivering To',
      etaMinutes: '10 min',
    },
    cart: {
      addressTypeHome: 'Home',
      addAddress: 'Add Address',
      failedToPlaceOrder: 'Failed to place order. Try again.',
      savedThisOrder: (amount: number) => `Yay! You saved ₹${amount} on this order`,
      newBadge: 'NEW',
      applyCouponsPromo: 'Apply coupons + payment offers & save more',
      arrivingOn: (dateLabel: string, slotShort: string) => `Arriving on ${dateLabel}, ${slotShort}`,
      shipmentScheduled: 'Shipment scheduled',
      edit: 'Edit',
      deliveringIn6Mins: 'Delivering in 6 mins',
      itemsCount: (n: number) => `${n} item${n !== 1 ? 's' : ''}`,
      schedule: 'Schedule',
      addFromWishlist: 'Add items from your wishlist',
      add: 'Add',
      bestDeals: 'Best Deals',
      giveATip: 'Give a Tip',
      deliveryInstructions: 'Delivery Instructions',
      tipDeliveryPartner: 'Tip Delivery Partner',
      tipSubtitle: "Help them earn a little extra for their effort.\n100% of this tip will go to them.",
      clearTip: 'Clear',
      customTip: 'Custom',
      enterAmountPlaceholder: 'Enter amount',
      apply: 'Apply',
      instructionsPlaceholder: 'E.g. Leave at door, call on arrival...',
      saved: 'Saved',
      save: 'Save',
      noBag: "I don't need a bag",
      toPay: 'TO PAY',
      payOnline: 'Pay Online',
      payCashUpi: 'PAY CASH/UPI',
      onDelivery: '(on delivery)',
      addDeliveryAddress: 'Add a delivery address',
      gotIt: 'Got it',
      dontMissSavings: "Don't miss extra savings!",
      applyCouponsToSaveMore: 'Apply coupons to save more',
      couponAppliedLabel: (code?: string) => `"${code} APPLIED"`,
      onlyUnitsAvailable: (stock: number) => `Only ${stock} unit(s) available`,
    },
    products: {
      defaultTitle: 'All Products',
      searchPlaceholder: 'Search products...',
      failedToLoadProducts: 'Failed to load products.',
      noProductsFound: 'No products found.',
    },
    categoryDetail: {
      defaultTitle: 'Products',
      allChip: 'All',
      priceAsc: 'Price ↑',
      priceDesc: 'Price ↓',
      discount: 'Discount',
      sort: 'Sort',
      brand: 'Brand',
      brandCount: (n: number) => `Brand (${n})`,
      offers: 'Offers',
      inStock: 'In Stock',
      clear: 'Clear',
    },
    allCategoriesGrid: {
      sectionTitles: {
        grocery: 'Grocery & Kitchen',
        snacks: 'Snacks & Drinks',
        fashion: 'Fashion & Lifestyle',
        beauty: 'Beauty & Personal Care',
        household: 'Household Essentials',
        stores: 'Shop by Store',
      },
      tiles: {
        fv: 'Fruits &\nVegetables',
        dbe: 'Dairy, Bread\n& Eggs',
        arod: 'Atta, Rice,\nOil & Dals',
        mfe: 'Meat, Fish\n& Eggs',
        mdf: 'Masala &\nDry Fruits',
        bs: 'Breakfast\n& Sauces',
        pkf: 'Packaged\nFood',
        tcm: 'Tea, Coffee\n& More',
        icm: 'Ice Creams\n& More',
        ff: 'Frozen\nFood',
        sc: 'Sweet\nCravings',
        cdj: 'Cold Drinks\n& Juices',
        mu: 'Munchies',
        bc: 'Biscuits\n& Cookies',
        app: 'Apparel',
        jew: 'Jewellery',
        pcs: 'Personal Care\nStudio',
        skin: 'Skincare',
        mab: 'Makeup\n& Beauty',
        frag: 'Fragrance',
        bb: 'Bath &\nBody',
        hair: 'Haircare',
        babycare: 'Baby Care',
        pn: 'Protein &\nNutrition',
        pw: 'Pharmacy\n& Wellness',
        fh: 'Feminine\nHygiene',
        hn: 'Home\nNeeds',
        kd: 'Kitchen\n& Dining',
        ce: 'Cleaning\nEssentials',
        es: 'Electronics\nStore',
        pc: 'Pet Care',
        ts: 'Toys &\nSports',
        sb: 'Stationery\n& Books',
        pan: 'Paan\nCorner',
        gift: 'Gift\nStore',
        ayush: 'Ayush\nStore',
        pooja: 'Pooja\nStore',
        derma: 'Derma\nStore',
        global: 'Global\nStore',
        sports: 'Sports\nStore',
        gaming: 'Gaming\nGift Cards',
        babystore: 'Baby\nStore',
        auto: 'Automotive\nStore',
      },
    },
  },
  hi: {
    common: {
      search: 'खोजें',
      seeAll: 'सभी देखें ›',
      seeAllPlain: 'सभी देखें',
      cancel: 'रद्द करें',
      backToTop: 'ऊपर जाएं ↑',
      locked: 'लॉक',
      unlocked: 'अनलॉक',
      apply: 'लागू करें',
      ok: 'ठीक है',
    },
    tabBar: {
      home: 'होम',
      categories: 'श्रेणियाँ',
      buyAgain: 'फिर से खरीदें',
      deals: 'डील्स',
    },
    home: {
      deliveryTime: '7 मिनट',
      locationUnavailable: 'लोकेशन उपलब्ध नहीं है',
      searchHints: ['दूध', 'फल', 'सब्ज़ियां', 'ब्रेड', 'अंडे', 'चॉकलेट', 'मक्खन', 'चिप्स'],
      searchForPrefix: 'खोजें',
      handpickedEssentials: 'रोज़मर्रा की चुनिंदा ज़रूरतें',
      noProductsYet: 'अभी कोई प्रोडक्ट उपलब्ध नहीं है!',
      failedToLoadProducts: 'प्रोडक्ट लोड करने में विफल।',
      unlockFreeDelivery: 'फ्री डिलीवरी अनलॉक करें',
      freeDeliveryUnlocked: ' फ्री डिलीवरी अनलॉक हो गई!',
      shopMoreForDelivery: (amount: number) => `₹${amount} और खरीदें`,
      cartLabel: 'कार्ट',
      itemsCount: (n: number) => `${n} आइटम`,
      offersToggle: 'ऑफर्स  ↑',
      offersForYou: 'आपके लिए ऑफर्स',
      offersCountLabel: '3 ऑफर्स',
      freeDelivery: 'फ्री डिलीवरी',
      freeDeliveryUnlockedOnOrder: 'इस ऑर्डर पर अनलॉक हो गई!',
      addMoreToUnlockDelivery: (amount: number) => `अनलॉक करने के लिए ₹${amount} और जोड़ें`,
      off50: '₹50 की छूट',
      shopMoreFor50: 'लागू करने के लिए ₹599 और खरीदें',
      off100: '₹100 की छूट',
      shopMoreFor100: 'लागू करने के लिए ₹1199 और खरीदें',
    },
    allProducts: {
      screenTitle: 'सभी श्रेणियाँ',
    },
    previousOrders: {
      headerTitle: 'आपके ऑर्डर',
      noOrdersYet: 'अभी तक कोई ऑर्डर नहीं',
    },
    location: {
      permissionTitle: 'लोकेशन अनुमति',
      permissionMessage: 'आस-पास के स्टोर दिखाने के लिए QuickKart को आपकी लोकेशन तक पहुंच चाहिए।',
      askMeLater: 'बाद में पूछें',
      unknownLocation: 'अज्ञात लोकेशन',
      locationUnavailableCaps: 'लोकेशन उपलब्ध नहीं है',
      locationUnavailable: 'लोकेशन उपलब्ध नहीं है',
      couldNotRetrieveLocation: 'आपकी लोकेशन प्राप्त नहीं हो सकी।',
      permissionNotGranted: 'लोकेशन एक्सेस की अनुमति नहीं दी गई।',
      permissionPermanentlyDenied: 'लोकेशन एक्सेस स्थायी रूप से अस्वीकृत है। कृपया इसे सेटिंग्स में सक्षम करें।',
      loadingAddress: 'पता लोड हो रहा है...',
    },
    floatingCartPanel: {
      freeDeliveryUnlocked: 'फ्री डिलीवरी अनलॉक हो गई!',
    },
    priceFilterBadge: {
      all: 'सभी',
      under: 'तक',
      prices: 'सभी कीमतें',
    },
    shareProduct: {
      title: 'प्रोडक्ट शेयर करें',
      priceLabel: (price: number) => `₹${price}`,
      shareMessage: (name: string, price: number) => `${name} — ₹${price}\nQuickKart में खोलने के लिए स्कैन करें`,
      scanToOpen: 'QuickKart में खोलने के लिए स्कैन करें',
      shareQrCode: 'QR कोड शेयर करें',
    },
    productCard: {
      loginForNotifications: 'नोटिफिकेशन पाने के लिए कृपया लॉग इन करें',
      enableNotificationsInSettings: 'सेटिंग्स में नोटिफिकेशन चालू करें',
      willNotifyWhenBack: 'स्टॉक में आने पर हम आपको सूचित करेंगे!',
      failedToSubscribe: 'सब्सक्राइब करने में विफल। फिर से कोशिश करें।',
      outOfStock: 'यह आइटम स्टॉक में नहीं है',
      notify: 'सूचित करें',
      offAmount: (amount: number) => `₹${amount} की छूट`,
      add: 'जोड़ें',
    },
    stockBadge: {
      soldOut: 'स्टॉक खत्म',
    },
    productFilterSheet: {
      selectMaxPrice: 'अधिकतम कीमत चुनें',
      inStockOnly: 'केवल स्टॉक में मौजूद',
      offersOnly: 'केवल ऑफर वाले',
      filters: 'फ़िल्टर',
      moreFilters: 'और फ़िल्टर',
      clearAll: 'सभी हटाएं',
      showProductsCount: (n: number) => `${n} प्रोडक्ट दिखाएं`,
      showProducts: 'प्रोडक्ट दिखाएं',
    },
    banners: {
      failedToLoad: 'बैनर लोड करने में विफल',
    },
    categoryProducts: {
      noProductsInCategory: (name: string) => `हमें ${name} में कोई प्रोडक्ट नहीं मिला।`,
      noMatches: 'कोई मेल नहीं मिला',
      tryAdjustingFilters: 'अपने फ़िल्टर बदलकर देखें।',
    },
    brandProducts: {
      noProductsFound: 'कोई प्रोडक्ट नहीं मिला',
      noProductsFromBrand: (brand: string) => `हमें ${brand} से कोई प्रोडक्ट नहीं मिला।`,
      productsCount: (n: number) => `${n} प्रोडक्ट`,
    },
    coupons: {
      headerTitle: 'कूपन और ऑफर्स',
      haveACode: 'कोड है?',
      couponsTab: 'कूपन',
      paymentOffersTab: 'पेमेंट ऑफर्स',
      note: 'नोट: अब आप कूपन और पेमेंट ऑफर्स एक साथ लागू कर सकते हैं।',
      autoAppliedBrandAddOns: 'ऑटो-लागू ब्रांड ऐड-ऑन',
      haveACouponCodeTitle: 'कूपन कोड है? यहां लागू करें!',
      couponCodeLabel: 'कूपन कोड',
      enterCouponCodePlaceholder: 'कूपन कोड डालें',
    },
    productDetails: {
      loginForNotifications: 'नोटिफिकेशन पाने के लिए कृपया लॉग इन करें',
      notificationCancelled: 'नोटिफिकेशन रद्द की गई',
      enableNotificationsInSettings: 'सेटिंग्स में नोटिफिकेशन चालू करें',
      willNotifyWhenBackInStock: 'स्टॉक में वापस आने पर हम आपको सूचित करेंगे!',
      somethingWentWrong: 'कुछ गलत हो गया। फिर से कोशिश करें।',
      stockLimitReached: 'स्टॉक सीमा पूरी हो गई',
      discountOff: (pct: number) => `${pct}% की छूट`,
      viewAllBrandProducts: (brand: string) => `${brand} के सभी प्रोडक्ट देखें`,
      weightFallback: '1 यूनिट',
      inclusiveOfTaxes: 'सभी करों सहित',
      productDetailsHeading: 'प्रोडक्ट विवरण',
      pleaseWait: 'कृपया प्रतीक्षा करें…',
      notified: 'सूचित किया गया',
      notifyMe: 'मुझे सूचित करें',
      addToCart: 'कार्ट में जोड़ें',
      viewCart: 'कार्ट देखें',
    },
    orderTracking: {
      title: 'ऑर्डर ट्रैकिंग',
    },
    orderPlaced: {
      title: 'ऑर्डर प्लेस हो गया!',
      subtitle: 'आपका ऑर्डर कन्फर्म हो गया है\nऔर जल्द ही डिलीवर किया जाएगा।',
    },
    notifications: {
      orderPlacedTitle: '🛒 ऑर्डर प्लेस हो गया!',
      orderPlacedBody: (orderTotal: number) => `आपका ₹${orderTotal} का ऑर्डर सफलतापूर्वक प्लेस हो गया है। हम जल्द ही डिलीवर करेंगे!`,
      orderDeliveredTitle: '📦 ऑर्डर डिलीवर हो गया!',
      orderDeliveredBody: 'आपका ऑर्डर डिलीवर हो गया है। अपने सामान का आनंद लें!',
    },
    orderDetails: {
      pdfGenFailedTitle: 'PDF जनरेट करने में विफल',
      pdfGenFailedMessage: 'इनवॉइस जनरेट नहीं हो सका। कृपया फिर से कोशिश करें।',
      couldNotOpenFileTitle: 'फ़ाइल नहीं खुल सकी',
      couldNotOpenFileMessage: 'PDF सेव हो गई लेकिन खुल नहीं सकी। किसी PDF व्यूअर ऐप का उपयोग करें।',
      couldNotLoadOrder: 'ऑर्डर विवरण लोड नहीं हो सका।',
      orderIdLabel: (id: string) => `ऑर्डर #${id}`,
      itemsCount: (n: number) => `${n} आइटम`,
      getHelp: 'मदद लें',
      orderDelivered: 'ऑर्डर डिलीवर हो गया',
      orderCancelled: 'ऑर्डर रद्द किया गया',
      orderPlaced: 'ऑर्डर प्लेस हो गया',
      deliveredSubtitle: (date: string) => `आपका सामान ${date} को डिलीवर किया गया`,
      cancelledSubtitle: (date: string) => `ऑर्डर ${date} को रद्द किया गया`,
      placedSubtitle: (date: string) => `ऑर्डर ${date} को प्लेस किया गया। डिलीवरी प्रगति पर है।`,
      productsOrdered: 'ऑर्डर किए गए प्रोडक्ट',
      productSnapshotFallback: 'प्रोडक्ट स्नैपशॉट',
      unitSizeFallback: 'यूनिट साइज़',
      weightAndUnits: (weight: string, quantity: number) => `${weight}  •  ${quantity} यूनिट`,
      promoVoucherApplied: (code: string) => `प्रोमो वाउचर (${code}) लागू`,
      totalBill: 'कुल बिल',
      downloadInvoice: 'इनवॉइस / क्रेडिट नोट डाउनलोड करें',
      orderDetailsHeading: 'ऑर्डर विवरण',
      orderIdFieldLabel: 'ऑर्डर ID',
      receiverDetailsLabel: 'प्राप्तकर्ता विवरण',
      deliveryAddressLabel: 'डिलीवरी पता',
      orderPlacedAtLabel: 'ऑर्डर प्लेस किया गया',
      needHelpTitle: 'इस ऑर्डर में मदद चाहिए?',
      needHelpSubtitle: 'अपनी समस्या खोजें या चैट पर संपर्क करें',
    },
    previousOrdersCard: {
      orderStatus: (status: string) => `ऑर्डर ${status} `,
      placedAt: (dateString: string) => `${dateString} को प्लेस किया गया`,
      orderAgain: 'फिर से ऑर्डर करें',
    },
    buyAgain: {
      filterTabs: {
        all: 'सभी आइटम',
        fresh: 'फल और\nसब्ज़ियां',
        dairy: 'डेयरी\nप्रोडक्ट',
        snacks: 'स्नैक्स और\nड्रिंक्स',
        electronics: 'ग्रोसरी और\nकिचन',
      },
      headerTitle: 'फिर से खरीदें ',
      buyAgainSection: 'फिर से खरीदें',
      noOrdersYet: 'आपने अभी तक कुछ ऑर्डर नहीं किया है।',
      noBoughtItemsInCategory: 'इस श्रेणी में पहले खरीदे गए आइटम नहीं हैं।',
      allProducts: 'सभी प्रोडक्ट',
      noProductsAvailable: 'कोई प्रोडक्ट उपलब्ध नहीं है।',
      taglineLine1: 'वह जगह जो आपकी हर',
      taglineLine2: 'ज़रूरत पूरी करे',
    },
    managePayments: {
      headerTitle: 'पेमेंट्स प्रबंधित करें',
      upiManagementTitle: 'QuickKart UPI प्रबंधन',
      upiManagementSub: 'QuickKart UPI से जुड़ी हर चीज़ प्रबंधित करें',
      wallets: 'वॉलेट्स',
      amazonPayBalance: 'Amazon Pay बैलेंस',
      link: 'लिंक करें',
      payLater: 'पे लेटर',
      amazonPayLater: 'Amazon Pay Later',
    },
    wishlist: {
      headerTitle: 'विशलिस्ट',
      emptyTitle: 'आपकी विशलिस्ट खाली है',
      emptySubtitle: 'किसी भी प्रोडक्ट पर दिल के निशान को दबाकर उसे यहां सेव करें',
    },
    profileEdit: {
      headerTitle: 'प्रोफ़ाइल',
      failedToLoadProfile: 'प्रोफ़ाइल लोड करने में विफल',
      nameEmpty: 'नाम खाली नहीं हो सकता',
      success: 'सफल',
      profileUpdated: 'प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई',
      failedToUpdateProfile: 'प्रोफ़ाइल अपडेट करने में विफल',
      deleteAccountTitle: 'खाता हटाएं',
      deleteAccountConfirm: 'क्या आप वाकई चाहते हैं? इससे आपके सभी ऑर्डर, वॉलेट राशि और सक्रिय रेफरल कोड स्थायी रूप से हट जाएंगे।',
      failedToDeleteAccount: 'खाता हटाने से पहले कृपया साइन आउट करके फिर से साइन इन करें।',
      nameLabel: 'नाम *',
      namePlaceholder: 'आपका नाम',
      mobileLabel: 'मोबाइल नंबर *',
      mobilePlaceholder: 'मोबाइल नंबर',
      emailLabel: 'ईमेल पता *',
      emailPlaceholder: 'ईमेल पता',
      emailHint: 'हम आपको स्पैम नहीं करेंगे',
      saving: 'सेव हो रहा है...',
      submit: 'सबमिट करें',
      deleteAccountDesc: 'खाता हटाने से आपके सभी ऑर्डर, वॉलेट राशि और सक्रिय रेफरल कोड हट जाएंगे।',
    },
    rewards: {
      headerTitle: 'रिवॉर्ड्स',
    },
    refunds: {
      headerTitle: 'रिफंड',
      emptyTitle: 'अभी तक कोई रिफंड नहीं',
      emptySubtitle: 'रिफंड प्रोसेस होने पर यह यहां दिखाई देगा।',
    },
    policy: {
      headerTitle: 'नीतियां',
      emptyTitle: 'अभी तक कोई नीति नहीं',
      emptySubtitle: 'हमारी नीतियां और शर्तें जल्द ही यहां उपलब्ध होंगी।',
    },
    addressForm: {
      addAddressTitle: 'पता जोड़ें',
      editAddressTitle: 'पता संपादित करें',
      labelField: 'लेबल (घर / ऑफिस / अन्य)',
      labelPlaceholder: 'जैसे घर',
      houseNoField: 'मकान / फ्लैट नंबर',
      houseNoPlaceholder: 'जैसे 42B',
      apartmentField: 'अपार्टमेंट / सोसाइटी',
      apartmentPlaceholder: 'जैसे Sunrise Apartments',
      landmarkField: 'लैंडमार्क',
      landmarkPlaceholder: 'जैसे City Mall के पास',
      fullAddressField: 'पूरा पता',
      fullAddressPlaceholder: 'स्ट्रीट, शहर, पिन कोड',
      saveAddress: 'पता सेव करें',
      saving: 'सेव हो रहा है…',
    },
    addressCard: {
      default: 'डिफ़ॉल्ट',
      nearLandmark: (landmark: string) => `${landmark} के पास`,
      editAddress: 'पता संपादित करें',
    },
    addressList: {
      headerTitle: 'सेव किए गए पते',
      noSavedAddresses: 'कोई सेव किया गया पता नहीं',
      addNewAddress: 'नया पता जोड़ें',
    },
    profile: {
      headerTitle: 'प्रोफ़ाइल',
      errorTitle: 'त्रुटि',
      failedToLoadProfile: 'प्रोफ़ाइल लोड करने में विफल',
      logOutTitle: 'लॉग आउट',
      logOutConfirm: 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
      logoutFailed: 'लॉग आउट विफल रहा',
      suggestionThanksTitle: 'धन्यवाद!',
      suggestionThanksMessage: 'आपका सुझाव प्राप्त हो गया है।',
      yourOrders: 'आपके\nऑर्डर',
      helpAndSupport: 'सहायता और\nसपोर्ट',
      yourWishlist: 'आपकी\nविशलिस्ट',
      yourInformation: 'आपकी जानकारी',
      yourRefunds: 'आपके रिफंड',
      yourWishlistTitle: 'आपकी विशलिस्ट',
      eGiftCards: 'ई-गिफ्ट कार्ड',
      comingSoon: 'जल्द आ रहा है!',
      helpAndSupportTitle: 'सहायता और सपोर्ट',
      account: 'खाता',
      savedAddresses: 'सेव किए गए पते',
      addressesCount: (n: number) => `${n} पते`,
      editProfile: 'प्रोफ़ाइल संपादित करें',
      managePayments: 'पेमेंट्स प्रबंधित करें',
      rewards: 'रिवॉर्ड्स',
      other: 'अन्य',
      suggestProducts: 'प्रोडक्ट सुझाएं',
      policies: 'नीतियां',
      logOutButton: 'लॉग आउट',
      suggestSheetSub: "जो खोज रहे थे वह नहीं मिला? कृपया प्रोडक्ट सुझाएं",
      suggestPlaceholder: 'उन प्रोडक्ट्स के नाम लिखें जिन्हें आप Zepto पर देखना चाहेंगे।',
      send: 'भेजें',
      language: 'भाषा',
      selectLanguage: 'भाषा चुनें',
    },
    validators: {
      nameRequired: 'नाम आवश्यक है',
      contactRequired: 'संपर्क आवश्यक है',
      emailInvalid: 'ईमेल अमान्य है',
      emailRequired: 'ईमेल आवश्यक है',
      invalidEmail: 'अमान्य ईमेल',
      passwordMinLength: 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
      passwordsDoNotMatch: 'पासवर्ड मेल नहीं खाते',
      passwordRequired: 'पासवर्ड आवश्यक है',
    },
    auth: {
      pleaseFixFields: 'कृपया हाइलाइट किए गए फ़ील्ड ठीक करें।',
      loginFailed: 'लॉगिन विफल रहा। कृपया फिर से कोशिश करें।',
      welcomeToQuickkart: 'QuickKart में आपका स्वागत है',
      pleaseLoginToAccount: 'कृपया अपने खाते में लॉगिन करें',
      emailLabel: 'ईमेल',
      passwordLabel: 'पासवर्ड',
      loggingIn: 'लॉगिन हो रहा है...',
      login: 'लॉगिन',
      dontHaveAccount: 'खाता नहीं है?',
      signUp: ' साइन अप करें',
      createAnAccount: 'खाता बनाएं',
      joinAndStartShopping: 'QuickKart से जुड़ें और शॉपिंग शुरू करें',
      fullNameLabel: 'पूरा नाम',
      phoneNumberLabel: 'फ़ोन नंबर',
      confirmPasswordLabel: 'पासवर्ड की पुष्टि करें',
      creatingAccount: 'खाता बनाया जा रहा है...',
      signUpButton: 'साइन अप करें',
      alreadyHaveAccount: 'पहले से खाता है?',
      logIn: ' लॉग इन करें',
      failedToCreateAccount: 'खाता बनाने में विफल। कृपया फिर से कोशिश करें।',
    },
    searchHeader: {
      defaultPlaceholder: 'प्रोडक्ट खोजें...',
    },
    searchResults: {
      priceChipLabel: 'कीमत',
      resultsCount: (n: number) => `${n} परिणाम`,
      inSubCategory: (name: string) => ` "${name}" में`,
      forQuery: (query: string) => ` "${query}" के लिए`,
      noProductsForQuery: (query: string) => `"${query}" के लिए कोई प्रोडक्ट नहीं मिला`,
    },
    deals: {
      priceTabs: {
        under199: '₹199 तक',
        under299: '₹299 तक',
        under399: '₹399 तक',
        under499: '₹499 तक',
        allPrices: 'सभी कीमतें',
      },
      categorySections: {
        fresh: 'ताज़ी उपज',
        dairy: 'डेयरी प्रोडक्ट',
        snacks: 'स्नैक्स और पेय',
        electronics: 'किचन और अधिक',
      },
      saleTitle: 'सेल',
      salePicks: ' सेल पिक्स',
      itemsCount: (n: number) => `${n} आइटम`,
      seeAll: 'सभी देखें',
      noProductsUnder: (amount: string | number) => `₹${amount} तक कोई प्रोडक्ट नहीं`,
      thisRange: 'इस रेंज में',
      tryDifferentPriceRange: 'अलग कीमत सीमा आज़माएं',
    },
    scheduleModal: {
      scheduleYourOrder: 'अपना ऑर्डर शेड्यूल करें',
      oneShipment: '1 शिपमेंट',
      shipment: 'शिपमेंट',
      oneOfOne: '1 का 1',
      itemsCount: (n: number) => `${n} आइटम`,
      viewItems: 'आइटम देखें',
      highDemand: 'अधिक मांग!',
      instantUnavailableNote: 'इंस्टेंट डिलीवरी अस्थायी रूप से अनुपलब्ध है। बाद के लिए शेड्यूल करें।',
      instantDelivery: 'इंस्टेंट डिलीवरी',
      unavailable: 'अनुपलब्ध',
      scheduleDelivery: 'डिलीवरी शेड्यूल करें',
      dateSlotFormat: (dateLabel: string, slotDisplay: string) => `${dateLabel}, ${slotDisplay}`,
      selectASlot: 'एक स्लॉट चुनें',
      today: (dateLabel: string) => `आज, ${dateLabel}`,
      tomorrow: (dateLabel: string) => `कल, ${dateLabel}`,
      slotsCount: (n: number) => `${n} स्लॉट`,
      earliest: 'सबसे जल्दी',
      afternoon: 'दोपहर',
      evening: 'शाम',
      lessSlots: 'कम स्लॉट',
      moreSlots: 'अधिक स्लॉट',
      cancelNote: 'आप डिलीवरी के समय से 30 मिनट पहले तक रद्द कर सकते हैं',
      confirm: 'पुष्टि करें',
      shipmentOneOfOne: 'शिपमेंट 1 का 1',
      itemsCountLower: (n: number) => `${n} आइटम`,
      weightByQty: (weight: string, quantity: number) => `${weight} X ${quantity} पीस`,
    },
    savingsCard: {
      totalSavings: 'इस ऑर्डर पर कुल बचत',
      youSave: (amount: number) => `आपने ₹${amount} बचाए`,
    },
    deliveryTip: {
      tipDeliveryPartner: 'डिलीवरी पार्टनर को टिप दें',
      subtitle: '100% सीधे उन्हें जाता है',
      clear: 'हटाएं',
    },
    couponCard: {
      title: 'कूपन और ऑफर्स',
      viewCoupons: 'कूपन देखें',
      viewAllPaymentOffers: 'सभी पेमेंट ऑफर्स देखें >',
      remove: 'हटाएं',
      viewPaymentOffers: 'पेमेंट ऑफर्स देखें',
    },
    brandCoupon: {
      autoApplied: 'कूपन अपने आप लागू हो जाएगा',
      knowMore: 'और जानें',
      unlockLine: (unlockText: string) => `• यह ऑफर लागू करने के लिए ${unlockText}`,
      autoAppliedLine: '• चेकआउट पर कूपन अपने आप लागू हो जाएगा',
      validOnBrandLine: '• केवल इस ब्रांड के योग्य प्रोडक्ट्स पर मान्य',
    },
    billSummary: {
      title: 'बिल सारांश',
      itemTotal: 'आइटम कुल',
      deliveryFee: 'डिलीवरी शुल्क',
      free: 'मुफ़्त',
      freeAboveNote: (amount: number) => `₹99 से ऊपर मुफ़्त (₹${amount} और जोड़कर अनलॉक करें)`,
      handlingFee: 'हैंडलिंग शुल्क',
      deliveryTip: 'डिलीवरी टिप',
      toPay: 'भुगतान करें',
      savingsOnOrder: 'इस ऑर्डर पर बचत',
      discountOnMrp: 'MRP पर छूट',
    },
    addressSelector: {
      selectAddress: 'पता चुनें',
      addNewAddress: 'नया पता जोड़ें',
      savedAddresses: 'सेव किए गए पते',
      selected: 'चयनित',
      deleteAddressTitle: 'पता हटाएं',
      deleteAddressMessage: 'क्या आप वाकई इस पते को हटाना चाहते हैं?',
      delete: 'हटाएं',
    },
    addressHeader: {
      defaultTitle: 'घर',
      defaultAddress: 'आपके सेव किए गए पते पर डिलीवरी',
      deliveringTo: 'डिलीवरी यहां',
      etaMinutes: '10 मिनट',
    },
    cart: {
      addressTypeHome: 'घर',
      addAddress: 'पता जोड़ें',
      failedToPlaceOrder: 'ऑर्डर देने में विफल। फिर से कोशिश करें।',
      savedThisOrder: (amount: number) => `बधाई हो! आपने इस ऑर्डर पर ₹${amount} बचाए`,
      newBadge: 'नया',
      applyCouponsPromo: 'कूपन + पेमेंट ऑफर्स लागू करें और अधिक बचाएं',
      arrivingOn: (dateLabel: string, slotShort: string) => `${dateLabel}, ${slotShort} को पहुंचेगा`,
      shipmentScheduled: 'शिपमेंट शेड्यूल हो गई',
      edit: 'संपादित करें',
      deliveringIn6Mins: '6 मिनट में डिलीवरी',
      itemsCount: (n: number) => `${n} आइटम`,
      schedule: 'शेड्यूल करें',
      addFromWishlist: 'अपनी विशलिस्ट से आइटम जोड़ें',
      add: 'जोड़ें',
      bestDeals: 'बेस्ट डील्स',
      giveATip: 'टिप दें',
      deliveryInstructions: 'डिलीवरी निर्देश',
      tipDeliveryPartner: 'डिलीवरी पार्टनर को टिप दें',
      tipSubtitle: 'उनकी मेहनत के लिए थोड़ा अतिरिक्त कमाने में मदद करें।\nयह टिप 100% उन्हीं को जाएगी।',
      clearTip: 'हटाएं',
      customTip: 'कस्टम',
      enterAmountPlaceholder: 'राशि डालें',
      apply: 'लागू करें',
      instructionsPlaceholder: 'जैसे दरवाज़े पर छोड़ें, पहुंचने पर कॉल करें...',
      saved: 'सेव हो गया',
      save: 'सेव करें',
      noBag: 'मुझे बैग नहीं चाहिए',
      toPay: 'भुगतान राशि',
      payOnline: 'ऑनलाइन भुगतान करें',
      payCashUpi: 'कैश/UPI से भुगतान करें',
      onDelivery: '(डिलीवरी पर)',
      addDeliveryAddress: 'डिलीवरी पता जोड़ें',
      gotIt: 'समझ गया',
      dontMissSavings: 'अतिरिक्त बचत न चूकें!',
      applyCouponsToSaveMore: 'अधिक बचाने के लिए कूपन लागू करें',
      couponAppliedLabel: (code?: string) => `"${code} लागू किया गया"`,
      onlyUnitsAvailable: (stock: number) => `केवल ${stock} यूनिट उपलब्ध हैं`,
    },
    products: {
      defaultTitle: 'सभी प्रोडक्ट',
      searchPlaceholder: 'प्रोडक्ट खोजें...',
      failedToLoadProducts: 'प्रोडक्ट लोड करने में विफल।',
      noProductsFound: 'कोई प्रोडक्ट नहीं मिला।',
    },
    categoryDetail: {
      defaultTitle: 'प्रोडक्ट',
      allChip: 'सभी',
      priceAsc: 'कीमत ↑',
      priceDesc: 'कीमत ↓',
      discount: 'छूट',
      sort: 'क्रमबद्ध करें',
      brand: 'ब्रांड',
      brandCount: (n: number) => `ब्रांड (${n})`,
      offers: 'ऑफर्स',
      inStock: 'स्टॉक में',
      clear: 'हटाएं',
    },
    allCategoriesGrid: {
      sectionTitles: {
        grocery: 'ग्रोसरी और किचन',
        snacks: 'स्नैक्स और ड्रिंक्स',
        fashion: 'फैशन और लाइफस्टाइल',
        beauty: 'ब्यूटी और पर्सनल केयर',
        household: 'घरेलू ज़रूरतें',
        stores: 'स्टोर के अनुसार खरीदें',
      },
      tiles: {
        fv: 'फल और\nसब्ज़ियां',
        dbe: 'डेयरी, ब्रेड\nऔर अंडे',
        arod: 'आटा, चावल,\nतेल और दाल',
        mfe: 'मीट, फिश\nऔर अंडे',
        mdf: 'मसाला और\nड्राई फ्रूट्स',
        bs: 'नाश्ता\nऔर सॉस',
        pkf: 'पैकेज्ड\nफूड',
        tcm: 'चाय, कॉफी\nऔर अधिक',
        icm: 'आइसक्रीम\nऔर अधिक',
        ff: 'फ्रोज़न\nफूड',
        sc: 'मीठा\nखाना',
        cdj: 'कोल्ड ड्रिंक्स\nऔर जूस',
        mu: 'मुंचीज़',
        bc: 'बिस्किट\nऔर कुकीज़',
        app: 'परिधान',
        jew: 'ज्वेलरी',
        pcs: 'पर्सनल केयर\nस्टूडियो',
        skin: 'स्किनकेयर',
        mab: 'मेकअप\nऔर ब्यूटी',
        frag: 'फ्रेगरेंस',
        bb: 'बाथ और\nबॉडी',
        hair: 'हेयरकेयर',
        babycare: 'बेबी केयर',
        pn: 'प्रोटीन और\nन्यूट्रिशन',
        pw: 'फार्मेसी\nऔर वेलनेस',
        fh: 'फेमिनिन\nहाइजीन',
        hn: 'होम\nनीड्स',
        kd: 'किचन\nऔर डाइनिंग',
        ce: 'क्लीनिंग\nएसेंशियल्स',
        es: 'इलेक्ट्रॉनिक्स\nस्टोर',
        pc: 'पेट केयर',
        ts: 'टॉयज़ और\nस्पोर्ट्स',
        sb: 'स्टेशनरी\nऔर किताबें',
        pan: 'पान\nकॉर्नर',
        gift: 'गिफ्ट\nस्टोर',
        ayush: 'आयुष\nस्टोर',
        pooja: 'पूजा\nस्टोर',
        derma: 'डर्मा\nस्टोर',
        global: 'ग्लोबल\nस्टोर',
        sports: 'स्पोर्ट्स\nस्टोर',
        gaming: 'गेमिंग\nगिफ्ट कार्ड्स',
        babystore: 'बेबी\nस्टोर',
        auto: 'ऑटोमोटिव\nस्टोर',
      },
    },
  },
};

export type Language = keyof typeof strings;
export type TranslationSchema = (typeof strings)[Language];
