export type RootStackParamList = {
  Login: undefined;
  Signup: undefined;
  Home: undefined;
  AllProducts: undefined;
  Products: { category: string; categoryTitle: string };
  CategoryDetail: { category: string; categoryTitle: string };
  Cart: undefined;
  ProductDetails: { productJson: string };
  CategoryProducts: { category: string; subCategory?: string };
  BrandProducts: { brand: string };
  Coupons: { tab?: string };
  Banners: undefined;
  OrderTracking: undefined;
  Orders: undefined;
  PreviousOrders: undefined;
  OrderDetails: { orderId: string };
  Search: undefined;
  SearchResults: { query?: string };
  Profile: undefined;
  ProfileEdit: undefined;
  Wishlist: undefined;
  Rewards: undefined;
  Policy: undefined;
  Refunds: undefined;
  HelpSupport: undefined;
  ManagePayments: undefined;
  AddressList: undefined;
  AddressAdd: undefined;
  AddressEdit: { addressId: string };
  OrderPlaced: undefined;
};
