export type RootStackParamList = {
  Login: undefined;
  Signup: undefined;
  Home: undefined;
  AllProducts: undefined;
  Products: { category: string; categoryTitle: string };
  CategoryDetail: { category: string; categoryTitle: string; subCategory?: string };
  Cart: undefined;
  ProductDetails: { productJson: string };
  CategoryProducts: { category: string; subCategory?: string };
  BrandProducts: { brand: string };
  Coupons: { tab?: string };
  Banners: undefined;
  OrderTracking: undefined;
  Orders: undefined;
  PreviousOrders: undefined;
  OrderDetails: { orderId: string };
  Search: undefined;
  SearchResults: { query?: string; subCategory?: string };
  Profile: undefined;
  ProfileEdit: undefined;
  Wishlist: undefined;
  Rewards: undefined;
  Policy: undefined;
  Refunds: undefined;
  HelpSupport: undefined;
  FaqCategory: { categoryId: string; categoryTitle: string };
  GeneralInquiry: undefined;
  FaqDetail: { question: string; answer: string; category: string; hasContactFooter?: boolean; hasLink?: boolean };
  PaymentRelated: undefined;
  FeedbackSuggestions: undefined;
  OrderProductsRelated: undefined;
  GiftCard: undefined;
  NoCostEMI: undefined;
  WalletRelated: undefined;
  QuickkartClub: undefined;
  Referral: undefined;
  CocaColaCampaign: undefined;
  ManagePayments: undefined;
  AddressList: undefined;
  AddressAdd: undefined;
  AddressEdit: { addressId: string };
  OrderPlaced: undefined;
};
