import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  header: {
    backgroundColor: '#35035C',
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    color: '#fff',
    marginLeft: 10,
    fontWeight: '600',
  },
  bodyContainer: {
    flex: 1,
    backgroundColor: '#F4F4F8',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    marginHorizontal: 16,
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
  img: {
    width: 80,
    height: 80,
    borderRadius: 10,
    backgroundColor: '#F9F9F9',
  },
  firstChild: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  nameContainer: {
    flex: 1,
    marginLeft: 12,
  },
  name: {
    fontSize: 15,
    color: '#111',
    fontWeight: '600',
    lineHeight: 20,
  },
  price: {
    fontSize: 16,
    color: '#111',
    fontWeight: '800',
    marginTop: 6,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#35035C',
    borderRadius: 10,
    overflow: 'hidden',
  },
  qtyBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantity: {
    fontSize: 15,
    color: '#fff',
    fontWeight: '700',
    paddingHorizontal: 10,
    minWidth: 24,
    textAlign: 'center',
  },
  secondChild: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  separator: {
    height: 10,
  },
  weightContainer: {
    flexDirection: 'row',
    gap: 4,
    alignItems: 'center',
    backgroundColor: '#F5F0FF',
    paddingVertical: 6,
    borderRadius: 8,
    paddingHorizontal: 12,
  },
  weight: {
    fontSize: 13,
    color: '#35035C',
    fontWeight: '600',
  },
  btn: {
    backgroundColor: '#35035C',
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  btnText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '700',
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
});
